// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostIn.Data;

#nullable disable

namespace PostIn.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PostIn.Data.Entities.Articolo", b =>
                {
                    b.Property<int>("ID_Articolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorpoTesto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataOraCreazione")
                        .HasColumnType("TEXT");

                    b.Property<int>("FK_Autore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImmagineCopertina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID_Articolo");

                    b.HasIndex("FK_Autore");

                    b.ToTable("Articoli");
                });

            modelBuilder.Entity("PostIn.Data.Entities.ArticoloCategoria", b =>
                {
                    b.Property<int>("FK_Articolo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_Categoria")
                        .HasColumnType("INTEGER");

                    b.HasKey("FK_Articolo", "FK_Categoria");

                    b.HasIndex("FK_Categoria");

                    b.ToTable("ArticoloCategorie");
                });

            modelBuilder.Entity("PostIn.Data.Entities.Categoria", b =>
                {
                    b.Property<int>("ID_Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID_Categoria");

                    b.HasIndex("NomeCategoria")
                        .IsUnique();

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("PostIn.Data.Entities.CategoriaPreferita", b =>
                {
                    b.Property<int>("FK_Dipendente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_Categoria")
                        .HasColumnType("INTEGER");

                    b.HasKey("FK_Dipendente", "FK_Categoria");

                    b.HasIndex("FK_Categoria");

                    b.ToTable("CategoriePreferite");
                });

            modelBuilder.Entity("PostIn.Data.Entities.Commento", b =>
                {
                    b.Property<int>("ID_Commento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPubblicazione")
                        .HasColumnType("TEXT");

                    b.Property<int>("FK_Articolo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_Autore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestoCommento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID_Commento");

                    b.HasIndex("FK_Articolo");

                    b.HasIndex("FK_Autore");

                    b.ToTable("Commenti");
                });

            modelBuilder.Entity("PostIn.Data.Entities.Dipendente", b =>
                {
                    b.Property<int>("ID_Dipendente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ruolo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatoAccount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UltimoAccesso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID_Dipendente");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Dipendenti");
                });

            modelBuilder.Entity("PostIn.Data.Entities.IscrizioniFollow", b =>
                {
                    b.Property<int>("FK_Follower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_Followed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataInizioInterazione")
                        .HasColumnType("TEXT");

                    b.HasKey("FK_Follower", "FK_Followed");

                    b.HasIndex("FK_Followed");

                    b.ToTable("IscrizioniFollow", t =>
                        {
                            t.HasCheckConstraint("CK_IscrizioniFollow_NoSelfFollow", "\"FK_Follower\" <> \"FK_Followed\"");
                        });
                });

            modelBuilder.Entity("PostIn.Data.Entities.Like", b =>
                {
                    b.Property<int>("FK_Dipendente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_Articolo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataRilascio")
                        .HasColumnType("TEXT");

                    b.HasKey("FK_Dipendente", "FK_Articolo");

                    b.HasIndex("FK_Articolo");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("PostIn.Data.Entities.SalvataggioDaLeggere", b =>
                {
                    b.Property<int>("FK_Dipendente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_Articolo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataSalvataggio")
                        .HasColumnType("TEXT");

                    b.HasKey("FK_Dipendente", "FK_Articolo");

                    b.HasIndex("FK_Articolo");

                    b.ToTable("SalvataggiDaLeggere");
                });

            modelBuilder.Entity("PostIn.Data.Entities.Visualizzazione", b =>
                {
                    b.Property<int>("ID_Visualizzazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataOraVisualizzazione")
                        .HasColumnType("TEXT");

                    b.Property<int>("FK_Articolo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_Dipendente")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID_Visualizzazione");

                    b.HasIndex("FK_Articolo");

                    b.HasIndex("FK_Dipendente");

                    b.ToTable("Visualizzazioni");
                });

            modelBuilder.Entity("PostIn.Data.Entities.Articolo", b =>
                {
                    b.HasOne("PostIn.Data.Entities.Dipendente", "Autore")
                        .WithMany("Articoliscritti")
                        .HasForeignKey("FK_Autore")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autore");
                });

            modelBuilder.Entity("PostIn.Data.Entities.ArticoloCategoria", b =>
                {
                    b.HasOne("PostIn.Data.Entities.Articolo", "Articolo")
                        .WithMany("ArticoloCategorie")
                        .HasForeignKey("FK_Articolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PostIn.Data.Entities.Categoria", "Categoria")
                        .WithMany("ArticoloCategorie")
                        .HasForeignKey("FK_Categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articolo");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("PostIn.Data.Entities.CategoriaPreferita", b =>
                {
                    b.HasOne("PostIn.Data.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("FK_Categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PostIn.Data.Entities.Dipendente", "Dipendente")
                        .WithMany()
                        .HasForeignKey("FK_Dipendente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Dipendente");
                });

            modelBuilder.Entity("PostIn.Data.Entities.Commento", b =>
                {
                    b.HasOne("PostIn.Data.Entities.Articolo", "Articolo")
                        .WithMany("Commenti")
                        .HasForeignKey("FK_Articolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PostIn.Data.Entities.Dipendente", "Autore")
                        .WithMany("Commenti")
                        .HasForeignKey("FK_Autore")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articolo");

                    b.Navigation("Autore");
                });

            modelBuilder.Entity("PostIn.Data.Entities.IscrizioniFollow", b =>
                {
                    b.HasOne("PostIn.Data.Entities.Dipendente", "Followed")
                        .WithMany("Followers")
                        .HasForeignKey("FK_Followed")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PostIn.Data.Entities.Dipendente", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FK_Follower")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Followed");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("PostIn.Data.Entities.Like", b =>
                {
                    b.HasOne("PostIn.Data.Entities.Articolo", "Articolo")
                        .WithMany()
                        .HasForeignKey("FK_Articolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PostIn.Data.Entities.Dipendente", "Dipendente")
                        .WithMany()
                        .HasForeignKey("FK_Dipendente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articolo");

                    b.Navigation("Dipendente");
                });

            modelBuilder.Entity("PostIn.Data.Entities.SalvataggioDaLeggere", b =>
                {
                    b.HasOne("PostIn.Data.Entities.Articolo", "Articolo")
                        .WithMany()
                        .HasForeignKey("FK_Articolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PostIn.Data.Entities.Dipendente", "Dipendente")
                        .WithMany()
                        .HasForeignKey("FK_Dipendente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articolo");

                    b.Navigation("Dipendente");
                });

            modelBuilder.Entity("PostIn.Data.Entities.Visualizzazione", b =>
                {
                    b.HasOne("PostIn.Data.Entities.Articolo", "Articolo")
                        .WithMany("Visualizzazioni")
                        .HasForeignKey("FK_Articolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PostIn.Data.Entities.Dipendente", "Dipendente")
                        .WithMany("Visualizzazioni")
                        .HasForeignKey("FK_Dipendente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articolo");

                    b.Navigation("Dipendente");
                });

            modelBuilder.Entity("PostIn.Data.Entities.Articolo", b =>
                {
                    b.Navigation("ArticoloCategorie");

                    b.Navigation("Commenti");

                    b.Navigation("Visualizzazioni");
                });

            modelBuilder.Entity("PostIn.Data.Entities.Categoria", b =>
                {
                    b.Navigation("ArticoloCategorie");
                });

            modelBuilder.Entity("PostIn.Data.Entities.Dipendente", b =>
                {
                    b.Navigation("Articoliscritti");

                    b.Navigation("Commenti");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("Visualizzazioni");
                });
#pragma warning restore 612, 618
        }
    }
}
